package gt_box_encryption_test

import (
	"fmt"
	"github.com/george012/gtbox/gtbox_encryption"
	"testing"
)

func TestGTEncryptionFunctions(t *testing.T) {
	pre_en_str := "abcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcddabcdd"
	en_key := "test"
	alen := len(pre_en_str)
	en_Str := gtbox_encryption.GTEncryptionGo(pre_en_str, en_key)

	fmt.Printf("en_str[%s]%d", en_Str, alen)

	de_str := gtbox_encryption.GTDecryptionGo(en_Str, en_key)
	b_len := len(de_str)
	fmt.Printf("en_str[%s]%d", de_str, b_len)

}

func TestGTEnc(t *testing.T) {

	for i := 0; i < 100; i++ {
		pre_en_str := fmt.Sprintf("%d%v%d", i, "duratime.UnixDate", i+1)
		en_key := "test"
		alen := len(pre_en_str)
		en_Str := gtbox_encryption.GTEnc(pre_en_str, en_key)

		fmt.Printf("en_str[%s]%d\n", en_Str, alen)

		de_str := gtbox_encryption.GTDec(en_Str, en_key)
		b_len := len(de_str)
		fmt.Printf("en_str[%s]%d\n", de_str, b_len)
	}

}
